//Doctors

export const DOCTOR_REQUEST_PENDING = "DOCTOR_REQUEST_PENDING";
export const DOCTOR_REQUEST_SUCCESS = "DOCTOR_REQUEST_SUCCESS";
export const DOCTOR_REQUEST_FAILURE = "DOCTOR_REQUEST_PEFAILURE";
